Haskap.Workflow.Ui.MvcWebUi/Controllers/Process1Controller.cs
using AutoMapper;
using Haskap.DddBase.Utilities.Guids;
using Haskap.Workflow.Application.Contracts.Processes;
using Haskap.Workflow.Application.Contracts.Processes.Process1;
using Haskap.DddBase.Application.Dtos.Common.DataTable;
using Haskap.Workflow.Application.Dtos.Processes;
using Haskap.Workflow.Application.Dtos.Processes.Process1;
using Haskap.Workflow.Application.UseCaseServices.Processes.Process1;
using Haskap.Workflow.Domain.Process1Aggregate;
using Haskap.Workflow.Domain.ProcessAggregate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Haskap.Workflow.Ui.MvcWebUi.Controllers;

[Authorize]
public class Process1Controller : Controller
{
    private readonly Guid _process1Id = Guid.Parse("c60f6f61-5766-41e4-b7c1-f25c09dd64b3");
    private readonly IProcess1Service _process1Service;

    public Process1Controller(
        IProcess1Service process1Service)
    {
        _process1Service = process1Service;
    }

    public async Task<IActionResult> CreateRequest(CancellationToken cancellationToken = default)
    {
        ViewBag.Process1Id = _process1Id;
        return View();
    }

    [HttpPost]
    public async Task<Guid> CreateRequest(Guid processId, RequestDataInputDto requestDataInputDto, CancellationToken cancellationToken = default)
    {
        var requestId = await _process1Service.CreateRequest(processId, requestDataInputDto, cancellationToken);

        return requestId;
    }

    public async Task<IActionResult> SearchRequest(CancellationToken cancellationToken = default)
    {
        ViewBag.Process1Id = _process1Id;
        return View();
    }

    [HttpPost]
    public async Task<JsonResult> SearchRequest(SearchParamsInputDto inputDto, JqueryDataTableParam jqueryDataTableParam, CancellationToken cancellationToken = default)
    {
        var result = await _process1Service.SearchRequestAsync(inputDto, jqueryDataTableParam, cancellationToken);
        return Json(result);
    }

    [HttpGet("Process1/RequestDetail/{requestId}")]
    public async Task<IActionResult> RequestDetail(Guid requestId, CancellationToken cancellationToken)
    {
        var output = await _process1Service.GetRequestDetailAsync(requestId, cancellationToken);
        
        ViewBag.AvailablePaths = await _process1Service.GetAvailablePathsAsync(requestId, cancellationToken);

        return View(output);
    }

    [HttpDelete]
    public async Task DeleteRequest(DeleteRequestInputDto inputDto, CancellationToken cancellationToken = default)
    {
        await _process1Service.DeleteRequestAsync(inputDto, cancellationToken);
    }

    [HttpPost]
    public async Task MakeProgress(MakeProgressInputDto inputDto, CancellationToken cancellationToken = default)
    {
        await _process1Service.MakeProgressAsync(inputDto, cancellationToken);
    }


    /*
     * Datası farklı her bir progress için 
     * bunun gibi farklı methodlar oluşturulması gerekiyor
     * Çünkü gelen data farklı olacak
     */
    [HttpPost]
    public async Task MakeProgressWithNote(MakeProgressInputDto inputDto, NoteProgressDataInputDto progressDataInputDto, CancellationToken cancellationToken = default)
    {
        await _process1Service.MakeProgressWithNoteAsync(inputDto, progressDataInputDto, cancellationToken);
    }

    [HttpGet]
    public async Task<IActionResult> LoadProgressWithNoteViewComponent(MakeProgressInputDto inputDto, CancellationToken cancellationToken)
    {
        return ViewComponent(typeof(ViewComponents.Process1.ProgressWithNote), new { inputDto.RequestId, inputDto.CommandId });
    }
}

Haskap.Workflow.Ui.MvcWebUi/Views/Shared/Error - Copy.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Haskap.Workflow.Ui.MvcWebUi/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Haskap.DugunSalonu.Ui.MvcWebUi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Haskap.DugunSalonu.Ui.MvcWebUi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Haskap.DugunSalonu.Ui.MvcWebUi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Haskap.DugunSalonu.Ui.MvcWebUi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Haskap.Workflow.Ui.MvcWebUi/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    @*<link rel="stylesheet" href="~/lib/AdminLte_3_2_0/plugins/fontawesome-free/css/all.min.css">*@
    <link rel="stylesheet" href="~/lib/fontawesome_6_2_0/css/all.min.css">
    <link href="~/lib/adminlte_3_2_0/plugins/select2/css/select2.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/AdminLte_3_2_0/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <style>
        .loading {
            display: none;
            position: fixed;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba( 255, 255, 255, .8 ) url('/LoadingAnimation.gif') 50% 50% no-repeat;
        }

        .loading_text {
            position: fixed;
            z-index: 1000;
            top: 54%;
            left: 38%;
            font-family: Arial;
            font-size: large;
            /*color: midnightblue;*/
        }
    </style>

    <!-- Styles -->
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="hold-transition login-page">
    <!-- Preloader -->
    <div class="loading">
        <p>
            <span class="loading_text">Başlattığınız işlem devam etmektedir. Lütfen bekleyiniz...</span>
        </p>
        @*<img class="animation__shake loading_text" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">*@
    </div>

    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - İş Akışı - <a asp-area="" asp-controller="Process1" asp-action="CreateRequest">Ana Sayfa</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/adminlte_3_2_0/plugins/select2/js/select2.full.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/AdminLte_3_2_0/dist/js/adminlte.min.js"></script>
    <script src="~/lib/sweetalert/dist/sweetalert2.all.min.js"></script>

    <script>
        $(document).ajaxError(function (event, jqxhr, settings, thrownError) {
            let envelope = $.parseJSON(jqxhr.responseText);

            if (envelope && envelope.hasError) {
                let exceptionStackTrace = envelope.exceptionStackTrace ? envelope.exceptionStackTrace : '';
                Swal.fire(
                    'Hata',
                    envelope.exceptionMessage + "<br /><br />" + exceptionStackTrace,
                    'error'
                );
            }
            else {
                Swal.fire(
                    'Beklenmedik Hata',
                    jqxhr.responseText,
                    'error'
                );
            }
        });

        $(document).ajaxStart(function () {
            $(".loading").show();
        });
        $(document).ajaxStop(function () {
            if (redirectStarted) {
                return;
            }

            $(".loading").hide();
        });

        $(this).submit(function (e) {
            $(".loading").show();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>